id: I69E7F456
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1619
  ocr_info:
    timestamp: 03/21/23T14:10:28
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 22:24:45.861472+00:00
last_modified: 2024-02-28 22:24:45.861477+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1619
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1619
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྣར་ཐང་བརྒྱ་རྩ་ལས་འབྱུང་བའི་ཡི་དམ་ལྷ་ཚོགས་རྣམས་ཀྱི་སྒྲུབ་ཐབས་རྗེས་གནང་དང་བཅས་པའི་ཡི་གེ
  languages:
  - bo
  author: ཞུ་ཆེན་ཚུལ་ཁྲིམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9443326687209233
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN1621:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1621
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1621.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9443326687209233
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
